name: Build and Release

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Python component
        run: bun run build:py

      - name: Build Electron app
        run: bun run build

      - name: Run tests
        run: bun run test

  build:
    name: Build (${{ matrix.platform }})
    needs: test
    strategy:
      matrix:
        platform: [linux, windows, macos]
        include:
          - platform: linux
            os: ubuntu-latest
            build-script: build:linux
          - platform: windows
            os: windows-latest
            build-script: build:win
          - platform: macos
            os: macos-latest
            build-script: build:macos
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build ${{ matrix.platform }} package
        run: bun run ${{ matrix.build-script }}

      - name: Upload ${{ matrix.platform }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gutenbird-${{ matrix.platform }}
          path: release/
          retention-days: 7

  release:
    name: Create Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded artifacts
        run: ls -la

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gutenbird-linux/**/*
            gutenbird-windows/**/*
            gutenbird-macos/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
